<template>
  <ProjectHeader />
  <ProjectIntro />

  <section id="hero">
    <div class="container">
      <img src="/images/gotiny_hero.png" alt="GoTiny Screenshot" />
    </div>
  </section>

  <section id="features">
    <div class="container">
      <div class="feature">
        <div class="feature-image-wrapper">
          <video src="/images/gotiny_feature_snelheid.mp4" autoplay loop muted playsinline></video>
        </div>
        <div class="feature-text" v-if="lang === 'nl'">
          <h3>Gemaakt voor snelheid</h3>
          <p>
            Het verkrijgen van een korte link moet zo snel en pijnloos mogelijk zijn. Bij het maken van zowel de website als de API waar GoTiny op draait, is
            bij iedere stap gedacht aan het optimaliseren van de snelheid voor de gebruiker.
          </p>
          <p>
            De user interface wordt niet ververst na het maken van een korte link, zodat de gebruiker niet hoeft te wachten tot de pagina opnieuw geladen is. De
            app verandert simpelweg naar een scherm waarin meteen duidelijk wordt wat de korte link is.
          </p>
        </div>
        <div class="feature-text" v-else>
          <h3>Made for speed</h3>
          <p>
            To obtain a short link has to be quick and painless. While creating both the website and the API that GoTiny runs on, I thought about how to
            optimize speed and reduce hassle, every step of the way.
          </p>

          <p>
            The user interface doesn't refresh after submitting the form on the website, so the user doesn't have to wait for another page loading. The API runs
            on the same server, so the screen simply changes to output the short link.
          </p>
        </div>
      </div>
      <div class="feature">
        <div class="feature-image-wrapper">
          <img src="/images/gotiny_feature_leesbaarheid.jpg" alt="Leesbaarheid" />
        </div>
        <div class="feature-text" v-if="lang === 'nl'">
          <h3>Is dat een O of een 0?</h3>
          <p>
            GoTiny genereert voor iedere link een unieke code die de bezoeker naar de originele website doorstuurt. Bij het ontwerp van deze korte links stond
            één ding centraal: het oplezen en intypen van de link moet zo gemakkelijk mogelijk zijn.
          </p>
          <p>
            Zo bevatten links die met GoTiny worden gemaakt geen speciale karaters. Hoofdletters en karaters die te veel op elkaar lijken ook uitgesloten. Zelfs
            met deze restricties zijn er genoeg combinaties mogelijk om tot het jaar 2030 iedere seconde een nieuwe link op te vragen. Tegen die tijd zal ik een
            karakter toevoegen.
          </p>
        </div>
        <div class="feature-text" v-else>
          <h3>Is that an O or 0?</h3>
          <p>
            GoTiny generates a short code for every link that takes the user to the original website that was provided. During construction of those links, I
            focused on one thing: sharing them should be as easy as possible.
          </p>

          <p>
            Links generated by GoTiny don't include special characters. Capital letters and characters that closely resemble another character (e.g. 5/s or
            i/1/l) are also excluded. This way, the link will always be easy to read and users won't accidentally visit non-existing links.
          </p>
        </div>
      </div>
      <div class="feature">
        <div class="feature-image-wrapper">
          <img src="/images/gotiny_feature_integratie.jpg" alt="Integratie" />
        </div>
        <div class="feature-text" v-if="lang === 'nl'">
          <h3>Overal te integreren</h3>
          <p>
            Hoewel de website van GoTiny een snelle manier is om een korte link te maken, ligt het hart van de funcionaliteit in de API. Met veelzijdigheid in
            het achterhoofd is deze opgezet om gebruikt te kunnen worden in een breed scala aan applicaties.
          </p>
          <p>
            GoTiny filtert zelf de link uit iedere tekst die gegeven wordt. Een ontwikkelaar die gebruik wil maken van de API, hoeft dus geen extra werk te doen
            om de lange url schoon aan te leveren. Zo kan GoTiny ingezet worden in een chatbot in slechts een paar regels code.
          </p>
        </div>
        <div class="feature-text" v-else>
          <h3>Integrate everywhere</h3>
          <p>
            Despite gotiny.cc being an easy way to create short links, the core of generating tiny links quickly and easily is the API behind it. Because I
            wanted to make the functionality accessible to other developers so they can implement it in their projects as well, I created the
            <a href="https://github.com/robvanbakel/gotiny-sdk" target="_blank">GoTiny SDK</a>.
          </p>

          <p>
            GoTiny automatically filters the url out of any string that a user enters. This way, developers using the SDK don't have to provide a clean link,
            but can just feed an entire paragraph into GoTiny. The API will find the url and return a short link.
          </p>
        </div>
      </div>
    </div>
  </section>
  <Footer />
</template>

<script>
import ProjectHeader from "@/components/layout/ProjectHeader"
import ProjectIntro from "@/components/layout/ProjectIntro"
import Footer from "@/components/layout/Footer"

export default {
  components: { ProjectHeader, ProjectIntro, Footer },
  computed: {
    lang() {
      return this.$store.getters["lang"]
    },
    meta() {
      return this.$store.getters["meta"]
    },
    project() {
      return this.$store.getters["meta"].projects.find((project) => project.name === this.$route.name)
    },
  },
}
</script>

<style></style>
